export const demoProfiles = [
  {
    uid: "demo_1",
    displayName: "Rafiq Ahmed",
    username: "rafiq_ahmed",
    age: 22,
    gender: "Male",
    location: "Dhaka",
    bio: "Gaming lover 🎮 | Music enthusiast 🎵 | Looking for friends to hang out with on weekends!",
    avatar: "https://api.dicebear.com/9.x/adventurer/svg?seed=Rafiq",
    hourlyRate: 200,
    rating: 4.8,
    totalHires: 15,
    interests: ["Gaming", "Music", "Cricket", "Movies"],
    isOnline: true,
    isVerified: true,
    badges: [
      { id: "top", name: "Top Rated", icon: "⭐", color: "#fdcb6e" },
      { id: "friendly", name: "Super Friendly", icon: "😊", color: "#00b894" },
    ],
  },
  {
    uid: "demo_2",
    displayName: "Nusrat Jahan",
    username: "nusrat_j",
    age: 20,
    gender: "Female",
    location: "Chittagong",
    bio: "Bookworm 📚 | Coffee addict ☕ | Let's explore cafes together!",
    avatar: "https://api.dicebear.com/9.x/adventurer/svg?seed=Nusrat",
    hourlyRate: 250,
    rating: 4.9,
    totalHires: 23,
    interests: ["Reading", "Coffee", "Travel", "Photography"],
    isOnline: true,
    isVerified: true,
    badges: [
      { id: "popular", name: "Popular", icon: "🔥", color: "#e17055" },
      { id: "verified", name: "Verified", icon: "✅", color: "#00b894" },
    ],
  },
  {
    uid: "demo_3",
    displayName: "Karim Hossain",
    username: "karim_h",
    age: 24,
    gender: "Male",
    location: "Sylhet",
    bio: "Football fanatic ⚽ | Gym rat 💪 | Always up for adventure!",
    avatar: "https://api.dicebear.com/9.x/adventurer/svg?seed=Karim",
    hourlyRate: 300,
    rating: 4.7,
    totalHires: 31,
    interests: ["Football", "Gym", "Hiking", "Cooking"],
    isOnline: false,
    isVerified: true,
    badges: [
      { id: "athlete", name: "Athlete", icon: "🏃", color: "#6c5ce7" },
    ],
  },
  {
    uid: "demo_4",
    displayName: "Fatima Khan",
    username: "fatima_k",
    age: 21,
    gender: "Female",
    location: "Rajshahi",
    bio: "Art student 🎨 | Anime fan 🌸 | Looking for study partners!",
    avatar: "https://api.dicebear.com/9.x/adventurer/svg?seed=Fatima",
    hourlyRate: 150,
    rating: 5.0,
    totalHires: 8,
    interests: ["Art", "Anime", "Study", "Music"],
    isOnline: true,
    isVerified: true,
    badges: [
      { id: "new", name: "Rising Star", icon: "🌟", color: "#fdcb6e" },
      { id: "perfect", name: "Perfect Rating", icon: "💎", color: "#6c5ce7" },
    ],
  },
  {
    uid: "demo_5",
    displayName: "Tanvir Islam",
    username: "tanvir_i",
    age: 23,
    gender: "Male",
    location: "Dhaka",
    bio: "Tech geek 💻 | Startup dreamer 🚀 | Let's build something together!",
    avatar: "https://api.dicebear.com/9.x/adventurer/svg?seed=Tanvir",
    hourlyRate: 350,
    rating: 4.6,
    totalHires: 19,
    interests: ["Coding", "Startup", "AI", "Gaming"],
    isOnline: true,
    isVerified: true,
    badges: [
      { id: "tech", name: "Tech Pro", icon: "💻", color: "#0984e3" },
      { id: "mentor", name: "Mentor", icon: "🧠", color: "#6c5ce7" },
    ],
  },
  {
    uid: "demo_6",
    displayName: "Sadia Rahman",
    username: "sadia_r",
    age: 19,
    gender: "Female",
    location: "Khulna",
    bio: "Singer 🎤 | Drama lover 🎭 | Life is too short to be boring!",
    avatar: "https://api.dicebear.com/9.x/adventurer/svg?seed=Sadia",
    hourlyRate: 180,
    rating: 4.9,
    totalHires: 12,
    interests: ["Singing", "Drama", "Dance", "Movies"],
    isOnline: false,
    isVerified: true,
    badges: [
      { id: "creative", name: "Creative Soul", icon: "🎨", color: "#fd79a8" },
    ],
  },
];